sudo: false
before_script:
- cp .sample.env .env
- bundle exec rake db:create
- bundle exec rake db:schema:load
cache: bundler
language: ruby
rvm:
  - 2.0.0
env:
  - rspec spec/models
  - rspec spec/features
notifications:
  webhooks: https://181bd223.ngrok.com/webhook
