development: &default
  adapter: postgresql
  database: findit_development
  pool: 5
  timeout: 5000
  host: localhost

test: &test
  adapter: postgresql
  database: findit_test
  username: postgres

cucumber:
  <<: *test
