development:
  adapter: postgresql
  encoding: unicode
  database: findit_development
  host: localhost
  port: <%= ENV['BOXEN_POSTGRESQL_PORT'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: findit_test
  host: localhost
  port: <%= ENV['BOXEN_POSTGRESQL_PORT'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: findit_production
  host: localhost
